ci:
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: requirements-txt-fixer
    - id: trailing-whitespace

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.902
#     hooks:
#     - id: mypy
#
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-check-mock-methods
    - id: python-no-eval
    - id: python-no-log-warn
    - id: python-use-type-annotations
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
    - id: text-unicode-replacement-char

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
    - id: autopep8
      args:
        - "--in-place"
        - "--max-line-length=100"

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      additional_dependencies: ["toml"]

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      additional_dependencies: ["toml"]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
      args: [--nbqa-mutate]
    - id: nbqa-flake8
      additional_dependencies: [flake8==3.8.4]
      args: [--nbqa-mutate]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.3]
      args: [--nbqa-mutate, --py36-plus]
    - id: nbqa-isort
      additional_dependencies: [isort==5.6.4]
      args: [--nbqa-mutate]
